# Generated by Django 5.0.7 on 2024-07-21 12:44

import apps.pirostagram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirostagram', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.pirostagram.models.post_image_path),
        ),
    ]
